
package SillyBeans;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import virtualmachine.VirtualMachine;

/**
 * This panel holds the controls for the visual debugger
 * @author Daniel Nissenbaum
 */
public class DebuggingPanel extends javax.swing.JPanel {

    private VirtualMachine vm;
    private int mem1;
    private int mem2;

    
    /**
     * DebuggingPanel constructor
     */
    public DebuggingPanel() {
        initComponents();
    }

    /**
     * sets the virtual machine controlled by this panel
     * @param vm Virtual machine
     */
    public void setVM(VirtualMachine vm) {
        this.vm = vm;
    }

    /**
     * gets the registerPanel for VM
     * @return the registerPanel
     */
    public RegisterPanel getRegisterPanel() {
        return registerPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        locLabel = new javax.swing.JLabel();
        memLoc = new javax.swing.JTextField();
        dumpMemButton = new javax.swing.JButton();
        loc2 = new javax.swing.JTextField();
        valLabel = new javax.swing.JLabel();
        loc1Label = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        sbrk = new javax.swing.JButton();
        cbrk = new javax.swing.JButton();
        cbrkt = new javax.swing.JButton();
        loc2Label = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        memoryLabel = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        deasButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        breakpointArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        memoryArea = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        changeMem = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        stopButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        stepButton = new javax.swing.JButton();
        loc1 = new javax.swing.JTextField();
        registerPanel = new SillyBeans.RegisterPanel();

        setMinimumSize(new java.awt.Dimension(325, 812));

        locLabel.setText("loc:");

        dumpMemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/dumpMem.png"))); // NOI18N
        dumpMemButton.setText("Dump Mem");
        dumpMemButton.setToolTipText("Dump memory form loc 1 to loc 2");
        dumpMemButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dumpMemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dumpMemButtonActionPerformed(evt);
            }
        });

        loc2.setNextFocusableComponent(loc1);

        valLabel.setText("val:");

        loc1Label.setText("loc 1:");

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        sbrk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/sbrk.png"))); // NOI18N
        sbrk.setText("sbrk");
        sbrk.setToolTipText("Add breakpoint at location \"loc\"");
        sbrk.setFocusable(false);
        sbrk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sbrk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sbrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbrkActionPerformed(evt);
            }
        });
        jToolBar2.add(sbrk);

        cbrk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/cbrk.png"))); // NOI18N
        cbrk.setText("cbrk");
        cbrk.setToolTipText("Clear breakpoint at location \"loc\"");
        cbrk.setFocusable(false);
        cbrk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cbrk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cbrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrkActionPerformed(evt);
            }
        });
        jToolBar2.add(cbrk);

        cbrkt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/cbrkt.png"))); // NOI18N
        cbrkt.setText("cbrkt");
        cbrkt.setToolTipText("Clear breakpoint table");
        cbrkt.setFocusable(false);
        cbrkt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cbrkt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cbrkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrktActionPerformed(evt);
            }
        });
        jToolBar2.add(cbrkt);

        loc2Label.setText("loc 2:");

        registerLabel.setText("Registers");
        registerLabel.setToolTipText("Change registers by typing in and int and pressing enter");

        jLabel1.setText("loc:");

        memoryLabel.setText("Memory");

        deasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/deas.png"))); // NOI18N
        deasButton.setText("Deas");
        deasButton.setToolTipText("Deasemble byte code from loc 1 to loc 2");
        deasButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deasButtonActionPerformed(evt);
            }
        });

        breakpointArea.setEditable(false);
        breakpointArea.setColumns(10);
        breakpointArea.setRows(5);
        breakpointArea.setToolTipText("Breakpoint");
        breakpointArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Breakpoints", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        jScrollPane4.setViewportView(breakpointArea);

        memoryArea.setColumns(10);
        memoryArea.setRows(5);
        memoryArea.setToolTipText("Dumped memory");
        jScrollPane2.setViewportView(memoryArea);

        changeMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/chngMem.png"))); // NOI18N
        changeMem.setText("Change Mem");
        changeMem.setToolTipText("Change memory location \"loc\" to value \"val\"");
        changeMem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        changeMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMemActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/stop.png"))); // NOI18N
        stopButton.setText("Stop");
        stopButton.setToolTipText("Stop current debug");
        stopButton.setFocusable(false);
        stopButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(stopButton);

        goButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/run.png"))); // NOI18N
        goButton.setText("Go");
        goButton.setToolTipText("Continue execution from current PC location");
        goButton.setFocusable(false);
        goButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(goButton);

        stepButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SillyBeans/step.png"))); // NOI18N
        stepButton.setText("Step");
        stepButton.setToolTipText("Execute next instruction");
        stepButton.setFocusable(false);
        stepButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(stepButton);

        loc1.setNextFocusableComponent(loc2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .add(jSeparator4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(loc1Label)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, loc2Label))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(loc2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .add(loc1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(deasButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(dumpMemButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(1, 1, 1)
                                .add(memLoc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(valLabel)
                                .add(1, 1, 1)
                                .add(value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(changeMem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(locLabel)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(loc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jToolBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(89, 89, 89)
                                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(memoryLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(registerLabel)
                                    .add(registerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(loc1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(loc1Label)))
                    .add(deasButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(loc2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(loc2Label)))
                    .add(dumpMemButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(changeMem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(memLoc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel1)
                                .add(valLabel)))))
                .add(3, 3, 3)
                .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(memoryLabel)
                    .add(registerLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(registerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 3, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(loc)
                            .add(locLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jToolBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane4)))
        );

        jScrollPane1.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        vm.go();
    }//GEN-LAST:event_goButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        vm.exit();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        vm.step();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void deasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deasButtonActionPerformed
        try {
            int l1 = Integer.parseInt(loc1.getText());
            int l2 = Integer.parseInt(loc2.getText());
            String deas = vm.deas(l1, l2);
            JFrame frm = new JFrame("Deasembly: " + l1 + " - " + l2);
            JTextArea jta = new JTextArea();
            jta.setText(deas);
            jta.setEditable(false);
            JScrollPane jsp = new JScrollPane(jta);
            frm.setSize(150, 600);
            frm.add(jsp);
            //frm.pack();
            frm.setVisible(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Please input two integers.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deasButtonActionPerformed

    private void dumpMemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dumpMemButtonActionPerformed
        try {
            mem1 = Integer.parseInt(loc1.getText());
            mem2 = Integer.parseInt(loc2.getText());
            String mem = vm.getMem(mem1, mem2);
            memoryArea.setText(mem);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Please input two integers.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dumpMemButtonActionPerformed

    private void cbrktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrktActionPerformed
        vm.cbrkt();
        breakpointArea.setText(vm.getBRKT());
    }//GEN-LAST:event_cbrktActionPerformed

    private void sbrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbrkActionPerformed
        try {
            int l = Integer.parseInt(loc.getText());
            vm.sbrk(l);
            breakpointArea.setText(vm.getBRKT());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Please input an integer.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sbrkActionPerformed

    private void cbrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrkActionPerformed
        try {
            int l = Integer.parseInt(loc.getText());
            vm.cbrk(l);
            breakpointArea.setText(vm.getBRKT());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Please input an integer.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbrkActionPerformed

    private void changeMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMemActionPerformed
        try {
            int loc = Integer.parseInt(memLoc.getText());
            int val = Integer.parseInt(value.getText());
            vm.chngm(loc, val);
            refresh(vm.getPC(),vm.getStack(), vm.getCmp());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Please input two integers.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Error e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Memory out of Bounds",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_changeMemActionPerformed

    /**
     * refreshes all the components with correct data
     * @param counter program counter
     * @param stk stack register
     * @param cmp compare register
     */
    public void refresh(int counter, int stk, int cmp) {
        registerPanel.refresh(counter, stk, cmp);
        String mem = vm.getMem(mem1, mem2);
        memoryArea.setText(mem);
    }

    /**
     * sets the components on this panel
     * @param vm -virtual machine
     * @param regs register array
     * @param counter program counter
     * @param stk stack register
     * @param cmp compare register
     */
    public void setComponents(VirtualMachine vm, int[] regs, int counter, int stk, int cmp) {
        registerPanel.setComponents(vm, regs, counter, stk, cmp);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea breakpointArea;
    private javax.swing.JButton cbrk;
    private javax.swing.JButton cbrkt;
    private javax.swing.JButton changeMem;
    private javax.swing.JButton deasButton;
    private javax.swing.JButton dumpMemButton;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField loc1;
    private javax.swing.JLabel loc1Label;
    private javax.swing.JTextField loc2;
    private javax.swing.JLabel loc2Label;
    private javax.swing.JLabel locLabel;
    private javax.swing.JTextField memLoc;
    private javax.swing.JTextArea memoryArea;
    private javax.swing.JLabel memoryLabel;
    private javax.swing.JLabel registerLabel;
    private SillyBeans.RegisterPanel registerPanel;
    private javax.swing.JButton sbrk;
    private javax.swing.JButton stepButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel valLabel;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
