/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SillyBeans;

import virtualmachine.VirtualMachine;

/**
 * Class that hold all the register and their values
 * @author Daniel Nissenbaum
 */
public class RegisterPanel extends javax.swing.JPanel {

    private int registers[];
    private VirtualMachine vm;

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * sets the classes components
     * @param vm virtual machine
     * @param regs register array
     * @param counter program counter
     * @param stk stack register
     * @param cmp compare register
     */
    public void setComponents(VirtualMachine vm, int[] regs, int counter, int stk, int cmp) {
        registers = regs;
        this.vm = vm;
        refresh(counter, stk, cmp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r0 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        r6 = new javax.swing.JTextField();
        r7 = new javax.swing.JTextField();
        r8 = new javax.swing.JTextField();
        r9 = new javax.swing.JTextField();
        r0label = new javax.swing.JLabel();
        r1label = new javax.swing.JLabel();
        r2label = new javax.swing.JLabel();
        r3label = new javax.swing.JLabel();
        r4label = new javax.swing.JLabel();
        r5label = new javax.swing.JLabel();
        r6label = new javax.swing.JLabel();
        r7label = new javax.swing.JLabel();
        r8label = new javax.swing.JLabel();
        r9label = new javax.swing.JLabel();
        stack = new javax.swing.JTextField();
        stackLabel = new javax.swing.JLabel();
        cmprLabel = new javax.swing.JLabel();
        cmpr = new javax.swing.JTextField();
        pcLabel = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();

        r0.setToolTipText("Register");
        r0.setActionCommand("<Not Set>");
        r0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r0ActionPerformed(evt);
            }
        });

        r1.setToolTipText("Register");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setToolTipText("Register");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setToolTipText("Register");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r4.setToolTipText("Register");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        r5.setToolTipText("Register");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        r6.setToolTipText("Register");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });

        r7.setToolTipText("Register");
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });

        r8.setToolTipText("Register");
        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });

        r9.setToolTipText("Register");
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });

        r0label.setText("r0:");
        r0label.setToolTipText("Register");

        r1label.setText("r1:");
        r1label.setToolTipText("Register");

        r2label.setText("r2:");
        r2label.setToolTipText("Register");

        r3label.setText("r3:");
        r3label.setToolTipText("Register");

        r4label.setText("r4:");
        r4label.setToolTipText("Register");

        r5label.setText("r5:");
        r5label.setToolTipText("Register");

        r6label.setText("r6:");
        r6label.setToolTipText("Register");

        r7label.setText("r7:");
        r7label.setToolTipText("Register");

        r8label.setText("r8:");
        r8label.setToolTipText("Register");

        r9label.setText("r9:");
        r9label.setToolTipText("Register");

        stack.setToolTipText("Stack Register: 0 - OK, 1 - FULL, 2 - EMPTY");
        stack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackActionPerformed(evt);
            }
        });

        stackLabel.setText("Stack:");
        stackLabel.setToolTipText("Stack Register: 0 - OK, 1 - FULL, 2 - EMPTY");

        cmprLabel.setText("Cmpr:");
        cmprLabel.setToolTipText("Compare Register");

        cmpr.setToolTipText("Compare Register");
        cmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmprActionPerformed(evt);
            }
        });

        pcLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pcLabel.setText("PC:");
        pcLabel.setToolTipText("Program Counter");

        pc.setToolTipText("Program Counter");
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(stackLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stack))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pcLabel)
                            .add(r1label)
                            .add(r2label)
                            .add(r3label)
                            .add(r9label)
                            .add(r4label)
                            .add(r5label)
                            .add(r6label)
                            .add(r7label)
                            .add(r8label)
                            .add(r0label))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pc)
                            .add(r0)
                            .add(r1)
                            .add(r2)
                            .add(r3)
                            .add(r4)
                            .add(r5)
                            .add(r6)
                            .add(r7)
                            .add(r8)
                            .add(r9))))
                .add(1, 1, 1))
            .add(layout.createSequentialGroup()
                .add(cmprLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmpr, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pcLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r0label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r1label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r2label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r3label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r4label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r5label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r6label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r7label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r8label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(r9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(r9label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(stackLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmpr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmprLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * refreshes and updates the register panels
     */
    public void refresh(int counter, int stk, int cmp) {
        r0.setText("" + registers[0]);
        r1.setText("" + registers[1]);
        r2.setText("" + registers[2]);
        r3.setText("" + registers[3]);
        r4.setText("" + registers[4]);
        r5.setText("" + registers[5]);
        r6.setText("" + registers[6]);
        r7.setText("" + registers[7]);
        r8.setText("" + registers[8]);
        r9.setText("" + registers[9]);
        pc.setText("" + counter);
        stack.setText("" + stk);
        cmpr.setText("" + cmp);

    }

    private void r0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r0ActionPerformed
        try {
            registers[0] = Integer.parseInt(r0.getText());
            r0.setFocusable(false);
            r0.setFocusable(true);

        } catch (NumberFormatException e) {
            r0.setText("" + registers[0]);
        }
    }//GEN-LAST:event_r0ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        try {
            registers[1] = Integer.parseInt(r1.getText());
            r1.setFocusable(false);
            r1.setFocusable(true);
        } catch (NumberFormatException e) {
            r1.setText("" + registers[1]);
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        try {
            registers[2] = Integer.parseInt(r2.getText());
            r2.setFocusable(false);
            r2.setFocusable(true);
        } catch (NumberFormatException e) {
            r2.setText("" + registers[2]);
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        try {
            registers[3] = Integer.parseInt(r3.getText());
            r3.setFocusable(false);
            r3.setFocusable(true);
        } catch (NumberFormatException e) {
            r3.setText("" + registers[3]);
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        try {
            registers[4] = Integer.parseInt(r4.getText());
            r4.setFocusable(false);
            r4.setFocusable(true);
        } catch (NumberFormatException e) {
            r4.setText("" + registers[4]);
        }
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        try {
            registers[5] = Integer.parseInt(r5.getText());
            r5.setFocusable(false);
            r5.setFocusable(true);
        } catch (NumberFormatException e) {
            r5.setText("" + registers[5]);
        }
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        try {
            registers[6] = Integer.parseInt(r6.getText());
            r6.setFocusable(false);
            r6.setFocusable(true);
        } catch (NumberFormatException e) {
            r6.setText("" + registers[6]);
        }
    }//GEN-LAST:event_r6ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        try {
            registers[7] = Integer.parseInt(r7.getText());
            r7.setFocusable(false);
            r7.setFocusable(true);
        } catch (NumberFormatException e) {
            r7.setText("" + registers[7]);
        }
    }//GEN-LAST:event_r7ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
        try {
            registers[8] = Integer.parseInt(r8.getText());
            r8.setFocusable(false);
            r8.setFocusable(true);
        } catch (NumberFormatException e) {
            r8.setText("" + registers[8]);
        }
    }//GEN-LAST:event_r8ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
        try {
            registers[9] = Integer.parseInt(r9.getText());
            r9.setFocusable(false);
            r9.setFocusable(true);
        } catch (NumberFormatException e) {
            r9.setText("" + registers[9]);
        }
    }//GEN-LAST:event_r9ActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        try {
            vm.setPC(Integer.parseInt(pc.getText()));
            pc.setFocusable(false);
            pc.setFocusable(true);
        } catch (NumberFormatException e) {
            pc.setText("" + vm.getPC());
        }
    }//GEN-LAST:event_pcActionPerformed

    private void stackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackActionPerformed
        try {
            vm.setStack(Integer.parseInt(stack.getText()));
            stack.setFocusable(false);
            stack.setFocusable(true);
        } catch (NumberFormatException e) {
            stack.setText("" + vm.getStack());
        }
    }//GEN-LAST:event_stackActionPerformed

    private void cmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmprActionPerformed
        try {
            vm.setCmp(Integer.parseInt(cmpr.getText()));
            cmpr.setFocusable(false);
            cmpr.setFocusable(true);
        } catch (NumberFormatException e) {
            cmpr.setText("" + vm.getCmp());
        }
    }//GEN-LAST:event_cmprActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmpr;
    private javax.swing.JLabel cmprLabel;
    private javax.swing.JTextField pc;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JTextField r0;
    private javax.swing.JLabel r0label;
    private javax.swing.JTextField r1;
    private javax.swing.JLabel r1label;
    private javax.swing.JTextField r2;
    private javax.swing.JLabel r2label;
    private javax.swing.JTextField r3;
    private javax.swing.JLabel r3label;
    private javax.swing.JTextField r4;
    private javax.swing.JLabel r4label;
    private javax.swing.JTextField r5;
    private javax.swing.JLabel r5label;
    private javax.swing.JTextField r6;
    private javax.swing.JLabel r6label;
    private javax.swing.JTextField r7;
    private javax.swing.JLabel r7label;
    private javax.swing.JTextField r8;
    private javax.swing.JLabel r8label;
    private javax.swing.JTextField r9;
    private javax.swing.JLabel r9label;
    private javax.swing.JTextField stack;
    private javax.swing.JLabel stackLabel;
    // End of variables declaration//GEN-END:variables
}
